=== Theodor-Springmann-Stiftung/dok/generated/_RELATION_Werke-Akteure.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="_x002A_RELATION_Werke-Akteure" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="_x002A_RELATION_Werke-Akteure">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="AkteureRELATION_Werke-Akteure" index-key="Akteur " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:index index-name="VOKABULAR_zu-AkteurRELATION_Werke-Akteure" index-key="Beziehung " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="WerkeRELATION_Werke-Akteure" index-key="Werk " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAC/ksrKCu5xQJ+fLZQJWP5YAAAAAArck0V4AeZAAAAAAAAAAAAqAFIA
RQBMAEEAVABJAE8ATgBfAFcAZQByAGsAZQAtAEEAawB0AGUAdQByAGUAAAAAAAAA
12pwnFuPb0C0/FhWdMYk1QcAAAC/ksrKCu5xQJ+fLZQJWP5YSQBEAAAAAAAAANTw
v7SSBQpCrYmzpwJ+KWEAAAAAGutXMXgB5kAAAAAAAAAAAFcAZQByAGsAZQAAAAAA
AAB4qlVoH52cSJkqea64iMVVBwAAANTwv7SSBQpCrYmzpwJ+KWFJAEQAAAAAAAAA
KHeafSazhUe/GdmKaJD99wcAAADU8L+0kgUKQq2Js6cCfilhUwBvAHIAdABpAGUA
cgB0AGkAdABlAGwAAAAAAAAA4ZcXODU6mU+4LOgIJaJbIQcAAADU8L+0kgUKQq2J
s6cCfilhUgBlAGkAaABlAAAAAAAAANZ3macjWRJEkhoUsLnE5SkHAAAA1PC/tJIF
CkKtibOnAn4pYUoAYQBoAHIAAAAAAAAAEcFJiHRcukKNdJuNNMlTzwcAAAC/ksrK
Cu5xQJ+fLZQJWP5YVwBlAHIAawAAAAAAAACbuW1fV02SToHn/XZq0yYaAAAAAMjD
kGlzAeZAAAAAAAAAAAAqAFYATwBLAEEAQgBVAEwAQQBSAF8AegB1AC0AQQBrAHQA
ZQB1AHIAAAAAAAAAKjfFTsvOIEGl4NzUlEbXxgcAAACbuW1fV02SToHn/XZq0yYa
SQBEAAAAAAAAAGmvmWuaBmZCisUkQr4fTXcHAAAAm7ltX1dNkk6B5/12atMmGlAA
cgDkAGQAaQBrAGEAdAAAAAAAAAA+oQ2Gay6FT45C+Ii6KSCxBwAAAL+SysoK7nFA
n58tlAlY/lhCAGUAegBpAGUAaAB1AG4AZwAAAAAAAADIcn51N1EOQ5dCCbgwQ9P1
AAAAACj8K0l4AeZAAAAAAAAAAABBAGsAdABlAHUAcgBlAAAAAAAAAHBuLb2TBltA
omwiuelkSLQHAAAAyHJ+dTdRDkOXQgm4MEPT9UkARAAAAAAAAABV3i4sPVlpSoej
elScX9aqBwAAAMhyfnU3UQ5Dl0IJuDBD0/VOAGEAbQBlAAAAAAAAAIYvocOnnLJN
s5NYePNDPV0HAAAAv5LKygrucUCfny2UCVj+WEEAawB0AGUAdQByAAAAAAAAAN1K
MO8J8QlPpwrFv5I1d/UHAAAAv5LKygrucUCfny2UCVj+WEEAbgBnAGEAYgBlAAAA
AAAAAE5FpSMmj5pFvitnWcRT7McHAAAAv5LKygrucUCfny2UCVj+WEEAbgBtAGUA
cgBrAHUAbgBnAGUAbgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAUAAAAAAAAA
AAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="v5LKygrucUCfny2UCVj+WA==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1260"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="12pwnFuPb0C0/FhWdMYk1Q==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Werk" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="EcFJiHRcukKNdJuNNMlTzw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2310"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [Werke].[ID], [Werke].[Sortiertitel], [Werke].[Reihe], [Werke].[Jahr] FROM Werke ORDER BY [Sortiertitel], [Reihe], [Jahr]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="4"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440;1440;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="4320Twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Beziehung" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="PqENhmsuhU+OQviIuikgsQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2250"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [*VOKABULAR_zu-Akteur].ID, [*VOKABULAR_zu-Akteur].Prädikat FROM [*VOKABULAR_zu-Akteur] ORDER BY [Prädikat]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1950"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1950Twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Akteur" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="hi+hw6ecsk2zk1h480M9XQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2880"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [Akteure].[ID], [Akteure].[Name] FROM Akteure ORDER BY [Name]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440Twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Angabe" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="3Uow7wnxCU+nCsW/kjV39Q==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextFormat" type="2" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AppendOnly" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Anmerkungen" minOccurs="0" od:jetType="memo" od:sqlSType="ntext" od:textFormat="1">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="TextFormat" type="2" value="1"/>
<od:fieldProperty name="GUID" type="9" value="TkWlIyaPmkW+K2dZxFPsxw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2580"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AppendOnly" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Theodor-Springmann-Stiftung/dok/muster/_RELATION_Werke-Akteure.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="_RELATION_Werke-Akteure.xsd" generated="2023-05-21T18:31:53">
<_x002A_RELATION_Werke-Akteure>
<ID>5</ID>
<Werk>3</Werk>
<Beziehung>1</Beziehung>
<Akteur>1</Akteur>
<Angabe>unbezeichnet</Angabe>
</_x002A_RELATION_Werke-Akteure>
<_x002A_RELATION_Werke-Akteure>
<ID>6</ID>
<Werk>3</Werk>
<Beziehung>6</Beziehung>
<Akteur>3</Akteur>
</_x002A_RELATION_Werke-Akteure>
<_x002A_RELATION_Werke-Akteure>
<ID>7</ID>
<Werk>2</Werk>
<Beziehung>1</Beziehung>
<Akteur>2</Akteur>
<Angabe>unbezeichnet</Angabe>
</_x002A_RELATION_Werke-Akteure>
</dataroot>
