=== Theodor-Springmann-Stiftung/dok/generated/_RELATION_Inhalte-Akteure.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="_x002A_RELATION_Inhalte-Akteure" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="_x002A_RELATION_Inhalte-Akteure">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="AkteureRELATION_Manifestation-Akteure" index-key="Akteur " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="InhalteRELATION_Inhalte-Akteure" index-key="Inhalt " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:index index-name="VOKABULAR_zu-AkteurRELATION_Manifestation-Akteure" index-key="Beziehung " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAADHaA+m9lLVSoL6pb7oFucgAAAAAMwGwIp4AeZAAAAAAAAAAAAqAFIA
RQBMAEEAVABJAE8ATgBfAEkAbgBoAGEAbAB0AGUALQBBAGsAdABlAHUAcgBlAAAA
AAAAAGhh+qyOaxZFtwahVj+sf8YHAAAAx2gPpvZS1UqC+qW+6BbnIEkARAAAAAAA
AABrNIpmlVhRR40h57FH28IyAAAAAIgC8qR4AeZAAAAAAAAAAABJAG4AaABhAGwA
dABlAAAAAAAAAAcj72A8XndFivtrJ6zd72sHAAAAazSKZpVYUUeNIeexR9vCMkkA
RAAAAAAAAADYheVC39wXQ57PMalQqI8FBwAAAGs0imaVWFFHjSHnsUfbwjJTAG8A
cgB0AGkAZQByAHQAaQB0AGUAbAAAAAAAAABjJViHCqecQ6kbq5CkKpvYBwAAAGs0
imaVWFFHjSHnsUfbwjJPAGIAagBlAGsAdABuAHUAbQBtAGUAcgAAAAAAAABoOuP5
oi6YS4iCsluuSePgBwAAAGs0imaVWFFHjSHnsUfbwjJUAHkAcAAAAAAAAABkgelZ
BawjRYo3Fd1eVXMKBwAAAMdoD6b2UtVKgvqlvugW5yBJAG4AaABhAGwAdAAAAAAA
AACbuW1fV02SToHn/XZq0yYaAAAAAMjDkGlzAeZAAAAAAAAAAAAqAFYATwBLAEEA
QgBVAEwAQQBSAF8AegB1AC0AQQBrAHQAZQB1AHIAAAAAAAAAKjfFTsvOIEGl4NzU
lEbXxgcAAACbuW1fV02SToHn/XZq0yYaSQBEAAAAAAAAAGmvmWuaBmZCisUkQr4f
TXcHAAAAm7ltX1dNkk6B5/12atMmGlAAcgDkAGQAaQBrAGEAdAAAAAAAAABWVUIX
Jv9zSJNc1MD0PViKBwAAAMdoD6b2UtVKgvqlvugW5yBCAGUAegBpAGUAaAB1AG4A
ZwAAAAAAAADIcn51N1EOQ5dCCbgwQ9P1AAAAACj8K0l4AeZAAAAAAAAAAABBAGsA
dABlAHUAcgBlAAAAAAAAAHBuLb2TBltAomwiuelkSLQHAAAAyHJ+dTdRDkOXQgm4
MEPT9UkARAAAAAAAAADQOZ1EWTHESI4dnD1Dd9YHBwAAAMhyfnU3UQ5Dl0IJuDBD
0/VTAG8AcgB0AGkAZQByAG4AYQBtAGUAAAAAAAAAHNvSdSvXCUqCja7DkJI4hQcA
AADIcn51N1EOQ5dCCbgwQ9P1TABlAGIAZQBuAHMAZABhAHQAZQBuAAAAAAAAAJhG
RHF4lhFBpGAcCZa/vkEHAAAAx2gPpvZS1UqC+qW+6BbnIEEAawB0AGUAdQByAAAA
AAAAAGycMn/50btOuWCIURP2umkHAAAAx2gPpvZS1UqC+qW+6BbnIEEAbgBnAGEA
YgBlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAABQAAAAAAAAAAAAAAAAAAAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="x2gPpvZS1UqC+qW+6BbnIA==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="aGH6rI5rFkW3BqFWP6x/xg==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Inhalt" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="ZIHpWQWsI0WKNxXdXlVzCg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2550"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [Inhalte].[ID], [Inhalte].[Sortiertitel], [Inhalte].[Objektnummer], [Inhalte].[Typ] FROM Inhalte ORDER BY [Sortiertitel], [Objektnummer]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="4"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440;1440;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="4320Twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Beziehung" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="VlVCFyb/c0iTXNTA9D1Yig==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2400"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [*VOKABULAR_zu-Akteur].ID, [*VOKABULAR_zu-Akteur].Prädikat FROM [*VOKABULAR_zu-Akteur] ORDER BY [Prädikat]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440Twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Akteur" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="mEZEcXiWEUGkYBwJlr++QQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="3510"/>
<od:fieldProperty name="ColumnOrder" type="3" value="4"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [Akteure].[ID], [Akteure].[Sortiername], [Akteure].[Lebensdaten] FROM Akteure ORDER BY [Sortiername], [Lebensdaten]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="3"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="2880Twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Angabe" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="5"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextFormat" type="2" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AppendOnly" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="bJwyf/nRu065YIhRE/a6aQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Theodor-Springmann-Stiftung/dok/muster/_RELATION_Inhalte-Akteure.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="_RELATION_Inhalte-Akteure.xsd" generated="2023-05-21T18:31:40">
<_x002A_RELATION_Inhalte-Akteure>
<ID>1</ID>
<Inhalt>2</Inhalt>
<Beziehung>3</Beziehung>
<Akteur>4</Akteur>
<Angabe>Heinr. Ramberg del. G. G. Endner sc. 1796</Angabe>
</_x002A_RELATION_Inhalte-Akteure>
<_x002A_RELATION_Inhalte-Akteure>
<ID>2</ID>
<Inhalt>2</Inhalt>
<Beziehung>3</Beziehung>
<Akteur>5</Akteur>
<Angabe>Heinr. Ramberg del. G. G. Endner sc. 1796</Angabe>
</_x002A_RELATION_Inhalte-Akteure>
</dataroot>
