=== Theodor-Springmann-Stiftung/dok/muster/_RELATION_Werke-Orte.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="_x002A_RELATION_Werke-Orte" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="_x002A_RELATION_Werke-Orte">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="OrteRELATION_Werke-Orte" index-key="Ort " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:index index-name="VOKABULAR_zu-OrteRELATION_Werke-Orte" index-key="Beziehung " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="WerkeRELATION_Werke-Orte" index-key="Werk " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAABc7KcvHS8lTZPoOAxnEtFEAAAAAFufmmpzAeZAAAAAAAAAAAAqAFIA
RQBMAEEAVABJAE8ATgBfAFcAZQByAGsAZQAtAE8AcgB0AGUAAAAAAAAAXP7TZn0O
F0KjScZrzOb2nAcAAABc7KcvHS8lTZPoOAxnEtFESQBEAAAAAAAAANTwv7SSBQpC
rYmzpwJ+KWEAAAAAGutXMXgB5kAAAAAAAAAAAFcAZQByAGsAZQAAAAAAAAB4qlVo
H52cSJkqea64iMVVBwAAANTwv7SSBQpCrYmzpwJ+KWFJAEQAAAAAAAAAKHeafSaz
hUe/GdmKaJD99wcAAADU8L+0kgUKQq2Js6cCfilhUwBvAHIAdABpAGUAcgB0AGkA
dABlAGwAAAAAAAAA4ZcXODU6mU+4LOgIJaJbIQcAAADU8L+0kgUKQq2Js6cCfilh
UgBlAGkAaABlAAAAAAAAANZ3macjWRJEkhoUsLnE5SkHAAAA1PC/tJIFCkKtibOn
An4pYUoAYQBoAHIAAAAAAAAAJl+wZPlMgUqvarXg/w3y5gcAAABc7KcvHS8lTZPo
OAxnEtFEVwBlAHIAawAAAAAAAABpI2xRgOX7R7ut6KpbTpGzAAAAAIQB+2lzAeZA
AAAAAAAAAAAqAFYATwBLAEEAQgBVAEwAQQBSAF8AegB1AC0ATwByAHQAZQAAAAAA
AAA/oQAG7q9fQ5nCo3cfSX/8BwAAAGkjbFGA5ftHu63oqltOkbOuAAAAAAAAAKGq
26g8/YBNkODP7hIgA28HAAAAaSNsUYDl+0e7reiqW06Rs1AAcgDkAGQAaQBrAGEA
dAAAAAAAAAAMAK/IqSCGTK/q//AOmk+iBwAAAFzspy8dLyVNk+g4DGcS0URCAGUA
egBpAGUAaAB1AG4AZwAAAAAAAACd4cRcmFd6T5TIWvie6SHIAAAAAKBxCF9zAeZA
AAAAAAAAAABPAHIAdABlAAAAAAAAAKiqKXZkRrpPqQRd+RGSKtMHAAAAneHEXJhX
ek+UyFr4nukhyEkARAAAAAAAAADlPjsK+zN4TZ3vR/IHD2hXBwAAAJ3hxFyYV3pP
lMha+J7pIchPAHIAdAAAAAAAAACxk13qBgHoToeaeDhf10evBwAAAFzspy8dLyVN
k+g4DGcS0URPAHIAdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAUAAAAAAAAA
AAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="XOynLx0vJU2T6DgMZxLRRA==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="XP7TZn0OF0KjScZrzOb2nA==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Werk" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="Jl+wZPlMgUqvarXg/w3y5g==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [Werke].[ID], [Werke].[Sortiertitel], [Werke].[Reihe], [Werke].[Jahr] FROM Werke ORDER BY [Sortiertitel], [Reihe], [Jahr]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="4"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440;1440;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="4320Twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Beziehung" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="DACvyKkghkyv6v/wDppPog==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [*VOKABULAR_zu-Orte].[®], [*VOKABULAR_zu-Orte].Prädikat FROM [*VOKABULAR_zu-Orte] ORDER BY [Prädikat]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440Twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Ort" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="sZNd6gYB6E6Hmng4X9dHrw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [Orte].[ID], [Orte].[Ort] FROM Orte ORDER BY [Ort]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440Twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Theodor-Springmann-Stiftung/dok/muster/_RELATION_Werke-Orte.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="_RELATION_Werke-Orte.xsd" generated="2023-05-21T18:32:06">
<_x002A_RELATION_Werke-Orte>
<ID>1</ID>
<Werk>2</Werk>
<Beziehung>2</Beziehung>
<Ort>1</Ort>
</_x002A_RELATION_Werke-Orte>
<_x002A_RELATION_Werke-Orte>
<ID>2</ID>
<Werk>2</Werk>
<Beziehung>2</Beziehung>
<Ort>1</Ort>
</_x002A_RELATION_Werke-Orte>
</dataroot>
