=== Theodor-Springmann-Stiftung/dok/muster/Akteure.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Akteure" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Akteure">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:index index-name="Sortiername" index-key="Sortiername " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAADIcn51N1EOQ5dCCbgwQ9P1AAAAAIPpK0l4AeZAAAAAAAAAAABBAGsA
dABlAHUAcgBlAAAAAAAAAHBuLb2TBltAomwiuelkSLQHAAAAyHJ+dTdRDkOXQgm4
MEPT9UkARAAAAAAAAABV3i4sPVlpSoejelScX9aqBwAAAMhyfnU3UQ5Dl0IJuDBD
0/VOAGEAbQBlAAAAAAAAABzb0nUr1wlKgo2uw5CSOIUHAAAAyHJ+dTdRDkOXQgm4
MEPT9UwAZQBiAGUAbgBzAGQAYQB0AGUAbgAAAAAAAADWYSIPPTjRSI2L6GDl1EGT
BwAAAMhyfnU3UQ5Dl0IJuDBD0/VCAGUAcgB1AGYAAAAAAAAA+p4hJBhqaUWdk6ti
yYE+JgcAAADIcn51N1EOQ5dCCbgwQ9P1UABzAGUAdQBkAG8AbgB5AG0AZQAAAAAA
AADQOZ1EWTHESI4dnD1Dd9YHBwAAAMhyfnU3UQ5Dl0IJuDBD0/VTAG8AcgB0AGkA
ZQByAG4AYQBtAGUAAAAAAAAA2qy8EmcsxUW67OPIXXNu5wcAAADIcn51N1EOQ5dC
CbgwQ9P1QQBuAG0AZQByAGsAdQBuAGcAZQBuAAAAAAAAAJB4gwyVETRDu33PBtj2
gm8HAAAAyHJ+dTdRDkOXQgm4MEPT9UcATgBEAAAAAAAAAKhi8UuV5u5Hn+L525js
8mYHAAAAyHJ+dTdRDkOXQgm4MEPT9U8AcgBnAE4AYQBtAGUAAAAAAAAAnBy0fnRg
1k6ylnBywOEzuAcAAADIcn51N1EOQ5dCCbgwQ9P1TgBhAGMAaAB3AGUAaQBzAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAABQAAAAAAAAAAAAAAAAAAAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="yHJ+dTdRDkOXQgm4MEPT9Q==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="cG4tvZMGW0CibCK56WRItA==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Name" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="Vd4uLD1ZaUqHo3pUnF/Wqg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2190"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextFormat" type="2" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AppendOnly" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Lebensdaten" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1860"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="HNvSdSvXCUqCja7DkJI4hQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Beruf" minOccurs="0" od:jetType="memo" od:sqlSType="ntext" od:textFormat="1">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="TextFormat" type="2" value="1"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AppendOnly" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="1mEiDz040UiNi+hg5dRBkw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Pseudonyme" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextFormat" type="2" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AppendOnly" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="+p4hJBhqaUWdk6tiyYE+Jg==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Sortiername" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="0DmdRFkxxEiOHZw9Q3fWBw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1770"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Nachweis" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="nBy0fnRg1k6ylnBywOEzuA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Anmerkungen" minOccurs="0" od:jetType="memo" od:sqlSType="ntext" od:textFormat="1">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="TextFormat" type="2" value="1"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1950"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AppendOnly" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="2qy8EmcsxUW67OPIXXNu5w==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="GND" minOccurs="0" od:jetType="hyperlink" od:sqlSType="ntext" od:hyperlink="yes">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AppendOnly" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="kHiDDJURNEO7fc8G2PaCbw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="OrgName" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="qGLxS5Xm7kef4vnbmOzyZg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="3540"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextFormat" type="2" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AppendOnly" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Theodor-Springmann-Stiftung/dok/muster/Akteure.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Akteure.xsd" generated="2023-05-21T18:32:49">
<Akteure>
<ID>1</ID>
<Name>Joseph Schreyvogel</Name>
<Lebensdaten>1768-1832</Lebensdaten>
<Beruf>&lt;div&gt;Autor&lt;/div&gt;</Beruf>
<Pseudonyme>C. A. West; Karl August West; Thomas West; West</Pseudonyme>
<Sortiername>Schreyvogel, Joseph</Sortiername>
<Nachweis>Goed IX/2, 2; E 325</Nachweis>
</Akteure>
<Akteure>
<ID>2</ID>
<Name>Wenzel Tremler</Name>
<Lebensdaten>1770-1851</Lebensdaten>
<Beruf>&lt;div&gt;Autor, Herausgeber&lt;/div&gt;</Beruf>
<Pseudonyme>Lembert; J. W. Lembert</Pseudonyme>
<Sortiername>Tremler, Wenzel</Sortiername>
<Nachweis>Goed IX, 29; H/B 161</Nachweis>
</Akteure>
<Akteure>
<ID>3</ID>
<Name>Johann Baptist Wallishauser</Name>
<Beruf>&lt;div&gt;Herausgeber, Drucker&lt;/div&gt;</Beruf>
<Sortiername>Wallishauser, Johann Baptist</Sortiername>
<Nachweis>DBI 2142</Nachweis>
</Akteure>
<Akteure>
<ID>4</ID>
<Name>Johann Heinrich Ramberg</Name>
<Lebensdaten>1763-1840</Lebensdaten>
<Beruf>&lt;div&gt;Graphiker&lt;/div&gt;</Beruf>
<Sortiername>Ramberg, Johann Heinrich</Sortiername>
<Nachweis>T/B XXVII, 587</Nachweis>
</Akteure>
<Akteure>
<ID>5</ID>
<Name>Eduard Ender</Name>
<Lebensdaten>1822-1883</Lebensdaten>
<Beruf>&lt;div&gt;Graphiker&lt;/div&gt;</Beruf>
<Sortiername>Ender, Eduard</Sortiername>
<Nachweis>T/B X, 515</Nachweis>
</Akteure>
</dataroot>
