=== Theodor-Springmann-Stiftung/dok/muster/Werke.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Werke" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Werke">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="Ausgabe-Nummer" index-key="Ausgabe-Nummer " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:index index-name="ReihenWerke" index-key="Reihe " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="Sortiertitel" index-key="Sortiertitel " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAADU8L+0kgUKQq2Js6cCfilhAAAAANZ3CF9zAeZAAAAAAAAAAABXAGUA
cgBrAGUAAAAAAAAAeKpVaB+dnEiZKnmuuIjFVQcAAADU8L+0kgUKQq2Js6cCfilh
SQBEAAAAAAAAAFFUDtc7Lo1HkmKqSEBw8vAHAAAA1PC/tJIFCkKtibOnAn4pYVUA
cgBoAGUAYgBlAHIAAAAAAAAAKHeafSazhUe/GdmKaJD99wcAAADU8L+0kgUKQq2J
s6cCfilhUwBvAHIAdABpAGUAcgB0AGkAdABlAGwAAAAAAAAAqtG4P5LEf0KN0PPl
uIbAEwcAAADU8L+0kgUKQq2Js6cCfilhVABpAHQAZQBsAAAAAAAAAD2rBFncjSND
v6esNrEyfQIAAAAAoHEIX3MB5kAAAAAAAAAAAFIAZQBpAGgAZQBuAAAAAAAAADW7
nq8xIxJDu6eVJ3CzNwUHAAAAPasEWdyNI0O/p6w2sTJ9AkkARAAAAAAAAAAe2bi8
/RmWRYBF/683v3XKBwAAAD2rBFncjSNDv6esNrEyfQJTAG8AcgB0AGkAZQByAHQA
aQB0AGUAbAAAAAAAAADhlxc4NTqZT7gs6AglolshBwAAANTwv7SSBQpCrYmzpwJ+
KWFSAGUAaQBoAGUAAAAAAAAA1neZpyNZEkSSGhSwucTlKQcAAADU8L+0kgUKQq2J
s6cCfilhSgBhAGgAcgAAAAAAAAA2YFtnCY0SSqjTEXc6R1jQBwAAANTwv7SSBQpC
rYmzpwJ+KWFBAHUAcwBnAGEAYgBlAC0ATgB1AG0AbQBlAHIAAAAAAAAAUpEqt+hD
RESGltbS/4qcHQcAAADU8L+0kgUKQq2Js6cCfilhUwB0AHIAdQBrAHQAdQByAAAA
AAAAAKR/zYFZhlVNqlJuMrOj4b8HAAAA1PC/tJIFCkKtibOnAn4pYU4AYQBjAGgA
dwBlAGkAcwAAAAAAAACh2ZqPZ2gETrL/z9B2K8iMBwAAANTwv7SSBQpCrYmzpwJ+
KWFBAG4AbQBlAHIAawB1AG4AZwBlAG4AAAAAAAAAdK/mr9wqLUKvGDV5anXVaAcA
AADU8L+0kgUKQq2Js6cCfilhRABFAFAAUgBfAEEATABNAE4AUgAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAADAAAAAUAAAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="1PC/tJIFCkKtibOnAn4pYQ==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2790"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="eKpVaB+dnEiZKnmuuIjFVQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Sortiertitel" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="KHeafSazhUe/GdmKaJD99w==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2010"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Titel" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="qtG4P5LEf0KN0PPluIbAEw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2070"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextFormat" type="2" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AppendOnly" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Reihe" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="4ZcXODU6mU+4LOgIJaJbIQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2610"/>
<od:fieldProperty name="ColumnOrder" type="3" value="4"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [Reihen].[ID], [Reihen].[Sortiertitel] FROM Reihen ORDER BY [Sortiertitel]; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440Twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Jahr" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="1neZpyNZEkSSGhSwucTlKQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="5"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowDatePicker" type="3" value="1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Ausgabe-Nummer" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="NmBbZwmNEkqo0xF3OkdY0A==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2490"/>
<od:fieldProperty name="ColumnOrder" type="3" value="6"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="7"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Struktur" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="UpEqt+hDRESGltbS/4qcHQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="7"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Nachweis" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1800"/>
<od:fieldProperty name="ColumnOrder" type="3" value="8"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="pH/NgVmGVU2qUm4ys6Phvw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Anmerkungen" minOccurs="0" od:jetType="memo" od:sqlSType="ntext" od:textFormat="1">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="TextFormat" type="2" value="1"/>
<od:fieldProperty name="GUID" type="9" value="odmaj2doBE6y/8/QdivIjA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="3450"/>
<od:fieldProperty name="ColumnOrder" type="3" value="9"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AppendOnly" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="DEPR_ALMNR" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="10"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="dK/mr9wqLUKvGDV5anXVaA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Theodor-Springmann-Stiftung/dok/muster/Werke.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Werke.xsd" generated="2023-05-21T18:35:03">
<Werke>
<ID>2</ID>
<Sortiertitel>AGLAJA. / TASCHENBUCH / für das Jahr 1825 / Elfter Jahrgang. / WIEN, / gedruckt und im Verlage / BEI JOH. BAPT. WALLISHAUSSER</Sortiertitel>
<Titel>AGLAJA. / TASCHENBUCH / für das Jahr 1825 / Elfter Jahrgang. / WIEN, / gedruckt und im Verlage / BEI JOH. BAPT. WALLISHAUSSER</Titel>
<Reihe>1</Reihe>
<Jahr>1825-01-01T00:00:00</Jahr>
<Ausgabe-Nummer>0</Ausgabe-Nummer>
<Struktur>UG, VB, verso G T, W, S 1 nT, 5 GG dazu 6 BB, SS 3-280, SS 281-282 I-Verz</Struktur>
<Nachweis>K 6; L/R 91; Goed IX. 33, 23; Goed VIII. 84,163</Nachweis>
<Anmerkungen>&lt;div&gt;Graphiken: Ergänzung durch Antiquariat G. Trauzettel Jan. 2010&lt;/div&gt;</Anmerkungen>
</Werke>
<Werke>
<ID>3</ID>
<Sortiertitel>AGLAJA. / Ein Taschenbuch / FÜR DAS JAHR / 1826 / Zwölfter Jahrgang. / WIEN, / gedruckt und im Verlage / BEI JOH. BAPT. WALLISHAUSSER</Sortiertitel>
<Titel>AGLAJA. / Ein Taschenbuch / FÜR DAS JAHR / 1826 / Zwölfter Jahrgang. / WIEN, / gedruckt und im Verlage / BEI JOH. BAPT. WALLISHAUSSER</Titel>
<Reihe>1</Reihe>
<Jahr>1826-01-01T00:00:00</Jahr>
<Ausgabe-Nummer>0</Ausgabe-Nummer>
<Struktur>UG, VB, verso G, T, T, S W, 5 GG dazu 6 BB G-Verz, S 1 nT, SS 3-289, S 290 I-Verz</Struktur>
<Nachweis>K 6; L/R 91; Goed IX. 33, 23; Goed VIII. 84,163</Nachweis>
<Anmerkungen>&lt;div&gt;# Hrsg 1826-1830 lt. Goed IX, 33: Wenzel Tremler; Pseud.: Lembert /) koll. außerdem: fremde Herkunft: Antiqu. G. Trauzettel; Jan. 2010&lt;/div&gt;</Anmerkungen>
</Werke>
</dataroot>
